config/routes.rb
Chatbot::Application.routes.draw do
  resources :stemmings

  resources :data

  resources :chats

  get "chat/index"
  post "chat/create"
  get "chat/store"

  get "chat/show"

   root 'chat#index'

  

end

app/models/stemming.rb
class Stemming
  include Mongoid::Document
  field :type, type: String
  field :keywords, type: String
  field :ganti, type: String
  field :kodisi, type: String
end

app/controllers/stemmings_controller.rb
class StemmingsController < ApplicationController
  before_action :set_stemming, only: [:show, :edit, :update, :destroy]

  # GET /stemmings
  # GET /stemmings.json
  def index
    @stemmings = Stemming.all
  end

  # GET /stemmings/1
  # GET /stemmings/1.json
  def show
  end

  # GET /stemmings/new
  def new
    @stemming = Stemming.new
  end

  # GET /stemmings/1/edit
  def edit
  end

  # POST /stemmings
  # POST /stemmings.json
  def create
    @stemming = Stemming.new(stemming_params)

    respond_to do |format|
      if @stemming.save
        format.html { redirect_to @stemming, notice: 'Stemming was successfully created.' }
        format.json { render action: 'show', status: :created, location: @stemming }
      else
        format.html { render action: 'new' }
        format.json { render json: @stemming.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stemmings/1
  # PATCH/PUT /stemmings/1.json
  def update
    respond_to do |format|
      if @stemming.update(stemming_params)
        format.html { redirect_to @stemming, notice: 'Stemming was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @stemming.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stemmings/1
  # DELETE /stemmings/1.json
  def destroy
    @stemming.destroy
    respond_to do |format|
      format.html { redirect_to stemmings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stemming
      @stemming = Stemming.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stemming_params
      params.require(:stemming).permit(:type, :keywords, :ganti, :kodisi)
    end
end

app/helpers/stemmings_helper.rb
module StemmingsHelper
end

app/views/stemmings/_form.html.erb
<%= form_for(@stemming) do |f| %>
  <% if @stemming.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stemming.errors.count, "error") %> prohibited this stemming from being saved:</h2>

      <ul>
      <% @stemming.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br>
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :ganti %><br>
    <%= f.text_field :ganti %>
  </div>
  <div class="field">
    <%= f.label :kodisi %><br>
    <%= f.text_field :kodisi %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stemmings/edit.html.erb
<h1>Editing stemming</h1>

<%= render 'form' %>

<%= link_to 'Show', @stemming %> |
<%= link_to 'Back', stemmings_path %>

app/views/stemmings/index.html.erb
<h1>Listing stemmings</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Keywords</th>
      <th>Ganti</th>
      <th>Kodisi</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stemmings.each do |stemming| %>
      <tr>
        <td><%= stemming.type %></td>
        <td><%= stemming.keywords %></td>
        <td><%= stemming.ganti %></td>
        <td><%= stemming.kodisi %></td>
        <td><%= link_to 'Show', stemming %></td>
        <td><%= link_to 'Edit', edit_stemming_path(stemming) %></td>
        <td><%= link_to 'Destroy', stemming, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stemming', new_stemming_path %>

app/views/stemmings/new.html.erb
<h1>New stemming</h1>

<%= render 'form' %>

<%= link_to 'Back', stemmings_path %>

app/views/stemmings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @stemming.type %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @stemming.keywords %>
</p>

<p>
  <strong>Ganti:</strong>
  <%= @stemming.ganti %>
</p>

<p>
  <strong>Kodisi:</strong>
  <%= @stemming.kodisi %>
</p>

<%= link_to 'Edit', edit_stemming_path(@stemming) %> |
<%= link_to 'Back', stemmings_path %>