config/routes.rb
Chatbot::Application.routes.draw do
  resources :stemmings

  resources :data

  resources :chats

  get "chat/index"
  post "chat/create"
  get "chat/store"

  get "chat/show"

   root 'chat#index'

  

end

app/models/chat.rb
class Chat
  include Mongoid::Document
  field :ip, type: String
  field :pesan, type: Hash
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController

  def create
   if cookies[:log]==nil or Chat.where(_id: cookies[:log]).count==0
    data={"ip"=> request.remote_ip, "pesan"=>{}}
    c=Chat.create(data)
    cookies[:log] = { :value => c._id, :expires => Time.now + 3600}
  else
    cookies[:log] = { :value => cookies[:log], :expires => Time.now + 3600}

  end
  kalimat=chat_params['pesan']
  if kalimat!=''
    Chat.where(_id: cookies[:log]).set(:pesan => insertpesan(kalimat))
    kalimat=kalimat.downcase
    Chat.where(_id: cookies[:log]).set(:pesan => insertpesan(jawab(cekkatatanya(kalimat.delete "?"),cektopik(kalimat.delete "?"))))
#    Chat.where(_id: cookies[:log]).set(:pesan => insertpesan(cekkatatanya(kalimat.delete "?")))
end
end

def show

  @chat=Chat.where(_id: cookies[:log]).last
  @cookies=cookies[:log]
  @topik=cookies[:topik]
  cookies[:log] = { :value => cookies[:log], :expires => Time.now + 3600}
  @scroll = params[:scroll];
end

def index

end

def jawab(tanya,topik)

  if topik!=nil
    if tanya["tanya"] == 'siapa' and topik.type== 'orang'
      tanya["tanya"]='apa'
    end
    case tanya["tanya"] 
    when 'apa'
      hasil= cekdata(topik.adalah)
    when 'lokasi'
      hasil= cekdata(topik.lokasi)
    when 'almamater'
      hasil= cekdata(topik.almamater,"#{topik.topik} lulusan dari")
    when 'kerja'
      hasil=cekdata(topik.pekerjaan,"Pekerjaan #{topik.topik} adalah ")
    when 'perusahaan'
      hasil=cekdata(topik.perusahaan,"Perusahaan dari #{topik.topik} adalah ")

    when 'siapa'
      hasil=cekdata(topik.oleh.to_s,"pendiri #{topik.topik} adalah")
    when 'kapan'
      di=(topik.type=="orang")? "dilahirkan" : "dibuat"
      hasil=cekdata(topik.kapan.to_s, " #{topik.topik} #{di} pada")
    when 'alamat'
      hasil= cekdata(topik.situs,"Alamat #{topik.topik} adalah")
    when 'platform'
      hasil=(topik.count==0)? "maaf data tidak ditemukan" : topik.platform.join(', ')
    when 'fitur'
      hasil=(topik.fitur==nil)? "maaf data tidak ditemukan" : topik.fitur.join(', ')

    when 'macamfitur'
      c = Datum.where(:fitur.in => tanya["param"])
      data=Array.new
      for i in 0..c.count-1
        data[i]=c[i].topik
      end
      hasil="aplikasi yang memiliki fitur #{tanya['param'][0]} antara lain " + data.join(', ')
    when 'macamplatform'
      c = Datum.where(:platform.in => tanya["param"])
      data=Array.new
      for i in 0..c.count-1
        data[i]=c[i].topik
      end
      hasil="aplikasi yang support dengan  #{tanya['param'][0]} antara lain " + data.join(', ')
    when 'macamsocmed'
      c = Datum.where(type: "socmed")
      data=Array.new
      for i in 0..c.count-1
        data[i]=c[i].topik
      end
      hasil="Macam socmed antara lain " + data.join(', ')
    else

      hasil=(tanya["tanya"]==nil)?  "maaf, silahkan menggunakan kata tanya"  : "maaf, data tidak ditemukan"    
    end

  else
    hasil="maaf, data tidak ditemukan"
  end



  return hasil


end

def cekdata(data, hasil=nil)

  hasil=(hasil==nil)? '': hasil ;
  return (data==nil)? "maaf data tidak ditemukan" : hasil +" " + data;
  
end
def insertpesan(data)
 chat=Chat.where(_id: cookies[:log]).last
 datapesan=chat.pesan
 ardata=(chat.pesan===nil)? 1 : datapesan.count+1; 

 datapesan[ardata]=data
 return datapesan
end
def chat_params
  params.permit(:pesan)
end

def cektopik(data)
  data=data.downcase
  ardata=data.split(' ')
  d= Datum.where(:keywords.in => ardata).first
  hasil=nil
  if d==nil
    hasil= Datum.where(_id: cookies[:topik] ).first
  else
    hasil=d
    cookies[:topik] = { :value => d._id, :expires => Time.now + 3600}
  end
  return hasil
end

def cekkatatanya(data)

  ardata=stemming(data)
  hasil={}
  tanya={}
  tanya["kerja"]= %w(kerja pekerjaan)
  tanya["lokasi"]= %w(lokasi tempat)
  tanya["perusahaan"]= %w(usaha instansi milik)
  tanya["almamater"]= %w(sekolah kuliah akademik universitas almamater kampus belajar)
  tanya["kapan"] = %w(kapan kpn)
  tanya["bagaimana"] = %w(gimana bagaimana gmn)
  tanya["siapa"]= %w(sapa siapa diri buat cipta)
  tanya["alamat"]= %w(alamat almt situs url domain)
  tanya["macam"]=%w(saja macam jenis)

  tanya["fitur"]=%w(fitur fasilitas)
  tanya["platform"]=%w(support platform device)
  tanya["apa"] = %w(apa adalah)
  tanya.each do | katanya |

    katatanya= katanya[0]
    tanya[katatanya].each do | datanya |
      if ardata.include? datanya
        hasil["tanya"]=katatanya
        break
      end
    end
    if hasil["tanya"]!=nil
      break
    end
  end
  katatanya=''
  datata=Array.new
  datamacam={}
  datamacam['macamfitur']= %w(chat video foto gambar musik mp3)
  datamacam['macamplatform']= %w(android web windows ios iphone symbian blackberry)
  datamacam['macamsocmed']= %w(jejaring sosial socmed social media)
  if hasil["tanya"]=="macam"
    datamacam.each do | katanya |

      katatanya = katanya[0]

      datamacam[katatanya].each do | datanya |

        if ardata.include? datanya
          hasil["tanya"]=katatanya
          hasil["param"]=[datanya]
          break
        end
      end

      if hasil["param"]!=nil
        break
      end
    end
  end  

  if hasil["tanya"]=="macam"
    tanya={}
    tanya["fitur"]= %w(fitur fasilitas)
    tanya["platform"]= %w(support platform device)


    tanya.each do | katanya |

      katatanya= katanya[0]
      tanya[katatanya].each do | datanya |
        if ardata.include? datanya
          hasil["tanya"]=katatanya
          break
        end
      end
      if hasil["tanya"]!='macam'
        break
      end
    end

  end
  return  hasil;
end
def stemming(kalimat)
 data=Array.new
 katakata=Kata.first
 ardata=kalimat.split(" ")
 for i in 0..ardata.count-1
  datatemp=ardata[i].stem
  data[i]=datatemp
  for y in 0..katakata.data.count-1
    if katakata.data[y] == datatemp
     data[i]=datatemp

     break
   end
   if Levenshtein.distance(katakata.data[y], datatemp) ==1
    data[i]=  katakata.data[y]
  else 
    if Levenshtein.distance(katakata.data[y], datatemp) ==2
    data[i]=  katakata.data[y]


  end
end
end
end
puts data
return data
end
def hapusawalan

end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  # GET /chats
  # GET /chats.json
  def index
    @chats = Chat.all
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @chat }
      else
        format.html { render action: 'new' }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
    respond_to do |format|
      format.html { redirect_to chats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_params
      params.require(:chat).permit(:ip, :pesan)
    end
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chat/_form.html.erb
<%= form_for(@chat) do |f| %>
  <% if @chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
      <% @chat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip %><br>
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :pesan %><br>
    <%= f.text_field :pesan %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chat/create.html.erb
<%= @chat %>

app/views/chat/edit.html.erb
<h1>Editing chat</h1>

<%= render 'form' %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chat/index.html.erb
<% javascript 'chat_index.js' %>
<div class="row" id="home">
<img src="/img/head.jpg">
</div>
 <div class="container">
<div id="tentang">
<h1>Apa sih Socmed?</h1>
<p> <img src="/img/social-media.jpg" class="img-rounded" style="float:left; margin-right:20px"> <b>Media sosial</b> atau yang biasa disebut socmed adalah sebuah media online, dengan para penggunanya bisa dengan mudah berpartisipasi, berbagi, dan menciptakan isi meliputi blog, jejaring sosial, wiki, forum dan dunia virtual. Blog, jejaring sosial dan wiki merupakan bentuk media sosial yang paling umum digunakan oleh masyarakat di seluruh dunia.
Andreas Kaplan dan Michael Haenlein mendefinisikan media sosial sebagai "sebuah kelompok aplikasi berbasis internet yang membangun di atas dasar ideologi dan teknologi Web 2.0 , dan yang memungkinkan penciptaan dan pertukaran user-generated content".
</p>
<p>
	Pesatnya perkembangan media sosial kini dikarenakan semua orang seperti bisa memiliki media sendiri. Jika untuk memiliki media tradisional seperti televisi, radio, atau koran dibutuhkan modal yang besar dan tenaga kerja yang banyak, maka lain halnya dengan media. Seorang pengguna media sosial bisa mengakses menggunakan media sosial dengan jaringan internet bahkan yang aksesnya lambat sekalipun, tanpa biaya besar, tanpa alat mahal dan dilakukan sendiri tanpa karyawan. Pengguna media sosial dengan bebas bisa mengedit, menambahkan, memodifikasi baik tulisan, gambar, video, grafis, dan berbagai model content lainnya.
	</p>
	<p>

Menurut Antony Mayfield dari iCrossing, media sosial adalah mengenai menjadi manusia biasa. Manusia biasa yang saling membagi ide, bekerjasama, dan berkolaborasi untuk menciptakan kreasi, berfikir, berdebat, menemukan orang yang bisa menjadi teman baik, menemukan pasangan, dan membangun sebuah komunitas. Intinya, menggunakan media sosial menjadikan kita sebagai diri sendiri. Selain kecepatan informasi yang bisa diakses dalam hitungan detik, menjadi diri sendiri dalam media sosial adalah alasan mengapa media sosial berkembang pesat. Tak terkecuali, keinginan untuk aktualisasi diri dan kebutuhan menciptakan personal branding.</p>
<br><br>
</div>
<div  id="chat">
<h1>Chat tentang Socmed</h1>
<%= @data %>
<div class="chat">

	<div class="tampil">
			
	</div>
<%= form_tag("/chat/create",:method => "post", :id => "formpesan" )  %>
	<input type='text' name="pesan" class="pesan" placeholder="Silahkan tulis pertanyaan anda" id="pesan">
	<input type='submit' class="btn btn-primary" value='Kirim'>
</form>
</div>
<footer>
fork on <a href="http://github.com/dedikisme/chatbot-rails">github</a>
</footer>
</div>
</div>

app/views/chat/new.html.erb
<h1>New chat</h1>

<%= render 'form' %>

<%= link_to 'Back', chats_path %>

app/views/chat/show.html.erb
<% javascript 'chat_show.js' %>
<table class="table table-striped">
    <tbody>
    	<%= @cookies %> 
<% for i in 1..@chat.pesan.count %>
 <tr>
    <td>
<% if (i%2==0)  %>
	<img src="/img/user.png" style="float:left;"><%= 'CS : ' %>
<% else %>
	<img src="/img/usergroup.png" style="float:left;"><%= 'You : ' %>
<% end %>
<%= @chat.pesan["#{i}"]  %>
	</td>
</tr>			
<% end %>
 </tbody>
</table>
<% if @scroll=='down' %>
<script>
window.location = "#down";
</script>
<% end %>
<div id="down"></div>

app/views/chat/store.html.erb
<h1>Chat#store</h1>
<p>Find me in app/views/chat/store.html.erb</p>