config/routes.rb
Chatbot::Application.routes.draw do
  resources :stemmings

  resources :data

  resources :chats

  get "chat/index"
  post "chat/create"
  get "chat/store"

  get "chat/show"

   root 'chat#index'

  

end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :set_datum, only: [:show, :edit, :update, :destroy]

  # GET /data
  # GET /data.json
  def index
    @data = Datum.all
  end

  # GET /data/1
  # GET /data/1.json
  def show
  end

  # GET /data/new
  def new
    @datum = Datum.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data
  # POST /data.json
  def create
    @datum = Datum.new(datum_params)

    respond_to do |format|
      if @datum.save
        format.html { redirect_to @datum, notice: 'Datum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @datum }
      else
        format.html { render action: 'new' }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1
  # PATCH/PUT /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to @datum, notice: 'Datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @datum.destroy
    respond_to do |format|
      format.html { redirect_to data_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datum_params
      params.require(:datum).permit(:topik, :keywords, :adalah, :oleh, :dimana, :bagaimana)
    end
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_form.html.erb
<%= form_for(@datum) do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
      <% @datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topik %><br>
    <%= f.text_field :topik %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br>
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :adalah %><br>
    <%= f.text_field :adalah %>
  </div>
  <div class="field">
    <%= f.label :oleh %><br>
    <%= f.text_field :oleh %>
  </div>
  <div class="field">
    <%= f.label :dimana %><br>
    <%= f.text_field :dimana %>
  </div>
  <div class="field">
    <%= f.label :bagaimana %><br>
    <%= f.text_field :bagaimana %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data/edit.html.erb
<h1>Editing datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/index.html.erb
<h1>Listing data</h1>

<table>
  <thead>
    <tr>
      <th>Topik</th>
      <th>Keywords</th>
      <th>Adalah</th>
      <th>Oleh</th>
      <th>Dimana</th>
      <th>Bagaimana</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @data.each do |datum| %>
      <tr>
        <td><%= datum.topik %></td>
        <td><%= datum.keywords %></td>
        <td><%= datum.adalah %></td>
        <td><%= datum.oleh %></td>
        <td><%= datum.dimana %></td>
        <td><%= datum.bagaimana %></td>
        <td><%= link_to 'Show', datum %></td>
        <td><%= link_to 'Edit', edit_datum_path(datum) %></td>
        <td><%= link_to 'Destroy', datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Datum', new_datum_path %>

app/views/data/new.html.erb
<h1>New datum</h1>

<%= render 'form' %>

<%= link_to 'Back', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topik:</strong>
  <%= @datum.topik %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @datum.keywords %>
</p>

<p>
  <strong>Adalah:</strong>
  <%= @datum.adalah %>
</p>

<p>
  <strong>Oleh:</strong>
  <%= @datum.oleh %>
</p>

<p>
  <strong>Dimana:</strong>
  <%= @datum.dimana %>
</p>

<p>
  <strong>Bagaimana:</strong>
  <%= @datum.bagaimana %>
</p>

<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>